### PR TITLE
Added DependencyInjection.VerifyConfiguration method

### LINKED ISSUE #20: Ability to verify DI-configuration
Dependency injection is great for testing, but to ensure that the dependency injection itself won't fail during runtime, it would be nice to have a built in ability for the DI-library to verify the configuration, for instance by scanning a given assembly and attempting to resolve the dependencies.

My suggestion would be a 'DependencyInjection.VerifyConfiguration(Assembly assembly)' method, with inspiration in the following:

```C#
using System;
using System.Reflection;
using AzureFunctions.Autofac;
using AzureFunctions.Autofac.Configuration;
using TodoAppBackend;
using Xunit;

namespace TodoAppBackendTest
{
    public class DITest
    {
        [Fact]
        public void TestDependencyInjection()
        {
            var assembly = typeof(DIConfig).Assembly;
            var classes = assembly.GetTypes();

            foreach (var c in classes)
            {
                var cAttr = c.GetCustomAttribute<DependencyInjectionConfigAttribute>();

                var injectAttrFound = false;

                var methods = c.GetMethods(BindingFlags.Public | BindingFlags.Static);
                foreach (var method in methods)
                {
                    var ps = method.GetParameters();
                    foreach (var param in ps)
                    {
                        var injectAttr = param.GetCustomAttribute<InjectAttribute>();

                        if (injectAttr == null)
                        {
                            continue;
                        }

                        // If this fails, DI-container is not set up on the class
                        Assert.NotNull(cAttr);

                        injectAttrFound = true;
                        var functionname = $"testfunction-{Guid.NewGuid()}";

                        // If this fails, the DI-config doesn't have the proper constructor
                        Activator.CreateInstance(cAttr.Config, functionname);

                        // If this fails, dependencies are not set up properly in the configuration
                        DependencyInjection.Resolve(param.ParameterType, injectAttr.Name, functionname);
                    }
                }

                if (!injectAttrFound)
                {
                    // If this fails, there is a DI-container but nothing to inject
                    Assert.Null(cAttr);
                }
            }

            Assert.True(true); // Dummy assertion to ensure that the test doesn't fail
        }
    }
};
```

If you like the idea, I would not be opposed to creating the feature.

### PR DESCRIPTION
**Pull request by ThorHelms**
# Description

Added DependencyInjection.VerifyConfiguration method, which allows the dependency injection configuration for a given type to be verified.
Also added a test-project to test the added functionality.

Fixes #20 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Added test-project and unit-tests to test the added functionality. Tested the following scenarios:
- Correct configuration
- Incorrect configuration
- Missing configuration
- Missing injection
- Missing injection can be ignored
- Neither configuration nor injection

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ThorHelms** [comment]
Just a note: I'm not 100% sure what the changes to the solution-file does, nor why they are there - it is merely something Visual Studio has changed on my behalf. Please let me know if the changes should be rolled back, and I'll happily do it.

**Review by rawrspace — COMMENTED** [review]
Looks good, the content that was removed from the sln was remnants of an older issue. All new added code does not affect existing functionality.

**Comment by rawrspace** [comment]
I submitted it to nuget as version 3.0.3. Should be up shortly. Thanks for contributing!

**Comment by ThorHelms** [comment]
Awesome, thank you very much :-)

**Pull request merged**
