### PR TITLE
Provide functions base directory to InjectionConfig

### LINKED ISSUE #38: Configuration Dependency Injection
```             
builder.Register(cfg =>
{
                    var config = new ConfigurationBuilder()
                        .SetBasePath(Directory.GetCurrentDirectory())
                        .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                        .AddEnvironmentVariables()
                        .Build();
                    MySection asc = new MySection();
                    config.GetSection("MySection").Bind(asc);
                    return Options.Create(asc);
}).As<IOptions<MySection>>();
```
Trying to do something like this but dont have any access to ExecutionContext to get the current directory

Have you got any recommendations

### PR DESCRIPTION
**Pull request by lxalln**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #38 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I have tested this against the local functions runtime, as well as against the Azure functions runtime.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by rawrspace — COMMENTED** [review]
Reviewing from my phone it looks good. I'll try to pull it down this week and verify functionality and do some regression testing.

**Comment by lxalln** [comment]
There is something extra in here that I wanted to take out.

```csharp
if (!DependencyInjection.IsInitialized(functionName))
```

This avoids multiple initialization for the same function, but is not related to this PR.

Wasn't sure how the draft PR process would work, but wanted to indicate that I was working on it.

**Comment by rawrspace** [comment]
Did you want to pull that out to a new PR or just include it in this PR?

**Comment by lxalln** [comment]
I think it'll be better as a separate PR. Unfortunately I've been ill so haven't had a chance to finish this last little bit off.

**Comment by lxalln** [comment]
I have removed the IsInitialized code, and will put that in a separate PR.

I am only on a linux laptop at the moment, so can't run the full dotnet framework tests. I can do this next week.

**Comment by rawrspace** [comment]
I think this looks good. I am going to edit the readme to be a bit clearer that the app directory is optional and then I will accept the PR. I am hoping to get to it tonight or this weekend. Thanks!

**Pull request merged**
