### PR TITLE
Feature/port services

### LINKED ISSUE #25: Register existing services when creating containers
I would like to have existing services that are registered by Azure Functions to be ported over to the created Autofac containers. The IWebJobsStartup implementation exposes 73 services in Microsoft.NET.Sdk.Functions 1.0.19. For example, the one I'm interested in is ILoggerFactory. 

image

I port the existing services in an ASP.Net project by referencing the Autofac.Extensions.DependencyInjection package which provides a ```builder.Populate(services)``` method (see https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L50). 

The problem this solves is that the Functions platform already has out of the box registrations that custom code could then build upon. These "existing" services are not currently available via the Autofac containers.

### PR DESCRIPTION
**Pull request by roryprimrose**
# Description

Refactors the providers so that existing Functions services are populated into the Autofac container.

Fixes #25 

## Type of change

- [x] Feature: Autofac containers now include out of the box service registrations that Autofac dependency resolutions can then use
- [x] Breaking: DI configuration classes must now inherit from Autofac.Module and provide a default constructor
- [x] Breaking: Mimimum full .net framework version increased from net46 to net461
- [x] Documentation: Updated to indicate changes to DI config class usage

# How Has This Been Tested?

Acceptance tests of the netstandard example project have been run to verify the container is created correctly with dependencies and OOTB services. Verified that the container is only created once per DI config class.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

**NOTE** 
- Existing unit tests covered DependencyInjection.VerifyConfiguration which has been removed in this PR. All impacted tests have also been removed
- Full framework test projects not run because of configuration failures.
- I am concerned that the full framework project does not have an equivalent ```DependencyInjectionStartup``` class and it isn't clear how the full framework version of the library configures this extension for an Azure Function. I suspect this is because the full framework targets an older version of the WebJobs package.

### CODE REVIEW

**Comment by roryprimrose** [comment]
I didn't change the version in the nuspec. This is definitely a breaking change.

**Comment by rawrspace** [comment]
Looks like something is causing the net framework example to fail:

> [9/5/2018 12:45:04 PM] Reading host configuration file 'C:\Users\CJ\source\repos\azure-function-autofac-dependency-injection\NetFrameworkExample\bin\Debug\net461\host.json'
[9/5/2018 12:45:04 PM] Host configuration file read:
[9/5/2018 12:45:04 PM] {}
[9/5/2018 12:45:04 PM] Starting Host (HostId=cjmain-664049673, Version=1.0.11913.0, InstanceId=331877dc-17f9-4b97-b31b-4b5118b6bad0, ProcessId=19012, AppDomainId=1, Debug=False, ConsecutiveErrors=3, StartupCount=4, FunctionsExtensionVersion=)
[9/5/2018 12:45:04 PM] Loaded custom extension 'BotFrameworkConfiguration'
[9/5/2018 12:45:04 PM] Loaded custom extension 'SendGridConfiguration'
[9/5/2018 12:45:04 PM] Loaded custom extension 'EventGridExtensionConfig'
[9/5/2018 12:45:04 PM] A ScriptHost error has occurred
[9/5/2018 12:45:04 PM] mscorlib: No parameterless constructor defined for this object.
[9/5/2018 12:45:04 PM] Stopping Host

I am looking into it and I will let you know if I find out why.

**Comment by roryprimrose** [comment]
Those host.json files are empty in the solution. I assumed that you have ```local.settings.json``` files on your machine that are not under source control to provide the configuration that would otherwise be in ```host.json``` in production.

**Comment by rawrspace** [comment]
I don't believe the issue is with the hosts.json file. The issue is with the fact that the InjectExtensionConfigProvider no longer has a parameterless constructor. This is fine for netstandard since it uses the DependencyInjectionStartup code but it causes a problem with netframework. I am looking now for a way to register the services through netframework.

**Comment by roryprimrose** [comment]
Alternatively, check out one of my older commits which was backward compatible for full .net when it was targeting net46 - https://github.com/roryprimrose/azure-function-autofac-dependency-injection/commit/f459f316998868f736d652a9a9d456f7e32e4336 

That commit supported both default constructor and IServiceCollection constructor.

**Comment by rawrspace** [comment]
Do you want to enable me to write to your branch https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ or would you prefer if I just pull your branch, make my changes, and submit a new PR?

**Comment by roryprimrose** [comment]
It looks like allow edits from maintainers is already enabled.

**Comment by rawrspace** [comment]
Alright, I'm stepping out but when I get home this evening I will check it out.

**Comment by roryprimrose** [comment]
No problem, I'm about to go to bed :)

**Comment by roryprimrose** [comment]
To be honest, I'm questioning the value of the core change here. Populating the OOTB services into the Autofac container is providing limited value if Autofac is not able to create many of the registered types. The thing I still like about this PR is changing the integration point to use Autofac modules rather than a constructor on DIConfig classes that make a static call to configure the ContainerBuilder.

**Comment by rawrspace** [comment]
Based on what you said I tried accessing the OOTB services like ILogger or ILoggerFactory and it doesn't seem to work for me. Looks like it is just missing some additional things that are not registered. Have you been able to resolve any of the OOTB services that get registered?

If you don't see a value in that functionality I have no personal need for it. I like what you have done with the modules instead of the static method call. I might just take that change.

**Comment by roryprimrose** [comment]
I have been able to resolve some but it is only ILoggerFactory that I'm after. I'm happy for you to take whatever you want from this PR and abandon the rest.

**Comment by rawrspace** [comment]
For now I am going to close out this PR but I will continue to keep this on the back burner as future enhancements

**Pull request closed without merging**
