### PR TITLE
Removed specific autofac version 

### PR DESCRIPTION
**Pull request by YoupHulsebos**
Removed specific autofac version. So that the package comsumer is free to update and redirect to a newer version.

# Description

Removed specific autofac version. So that the package comsumer is free to update and redirect to a newer version.

## Type of change

- [X ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] See the example soluton below. It has been deployed to azure on an app service plan

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rawrspace** [comment]
This issue is brought up from time to time, most recently in #29 where I explained that the version of Autofac that is required is set by Azure Functions and we have to match it.

If we do not match that version then the code will run locally but will fail when deployed into Azure. Recently in #47 we bumped up the version of Autofac to 4.6.2 to match the change Azure Functions made in order to restore functionality when deployed.

If you can provide a sample project that shows the updated version working when deployed into Azure then I would be happy to remove this requirement.

**Comment by YoupHulsebos** [comment]
Sure thing. See the attachted sample. It contains a solution with:
- An implementation project with the latest autofac
- An azure function project using the latest AzureFunctions.Autofac that has an build error
- An azure function project using the AzureFunctions.Autofac version of this pull request

I have deployed the "Resolved" project for you in azure. You can call the function on this url:
https://sample-autofac-update.azurewebsites.net/api/Function1?code=2PXMaqh1L1O1Bu8F5xvNxGFWdPBCYcQ4Du0MBd6LcJPxxfPeawChjg==

Or deploy the function yourself if you would like..

[Sample-AutoFac-Update.zip](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/files/4239218/Sample-AutoFac-Update.zip)

**Comment by YoupHulsebos** [comment]
@rawrspace Can you let me know if my attached samples and working function in azure made any difference in moving this issue forward?

**Comment by rawrspace** [comment]
I've been swamped these past couple weeks. I'll try to get to looking at the solution this week.

**Comment by YoupHulsebos** [comment]
Thanks for letting me know. Looking forward to your feedback.

**Comment by rawrspace** [comment]
I modified FancyImplementation.HowToSayHelloWorld() to return
`
return "Autofac Version:" + Assembly.GetAssembly(typeof(Container)).GetName().Version.ToString();
`
When I deployed to Azure it did indeed print 5.1.2

So it appears they may have in fact removed the restriction on the version. I will create an alpha package tomorrow and do some more testing before fulling pushing this out.

**Comment by YoupHulsebos** [comment]
Thanks you for reviewing this so quickly! Looking forward to the preview. Please let me know if I can be of assistance in any way

**Comment by rawrspace** [comment]
I am putting out an alpha build: https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.0-alpha Should be available shortly. I am going to do a bit more testing and then I will be releasing as v 4.0.0 since it is a major change.

**Comment by YoupHulsebos** [comment]
Thanks so much! I did my own testing with the new alpha and all our use cases work great. We have some time triggered and service bus triggered azure functions.

**Comment by aschaible** [comment]
This is impacting me as well... hope to see this merged soon.  Thanks!

**Comment by rawrspace** [comment]
@aschaible can you try the 4.0.0 alpha package and provide feedback? https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.0-alpha

I'm trying to confirm there are no issues before releasing it. It would be helpful to have more feedback from other users.

**Comment by rawrspace** [comment]
@YoupHulsebos @aschaible This has been merged into 4.0.0 which is pending release https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.0

Please let me know if you have any issues with the release package and thanks for contributing

**Pull request merged**
